/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;
 @SpringBootApplication(scanBasePackages = "springaop")
 @EnableAspectJAutoProxy
public class App {

    public static void main(String[] args)
    {
        System.out.println(new App().getGreeting());
    }
}
